### ISSUE TITLE
Implement Search Criteria in Nav Bar

### ISSUE THREAD

**Issue by jetamartin** [notch8/rent_my_thing#30]
I would suggest that we allow the user to specify/change  search criteria from any page in the application (e.g., Landing page, Index page). Given that we have a sticky Nav bar already this would be the most logical place to allow the user access to the search criteria. 

Implementation:   When user clicks on the "Search Thing" in the Nav bar they are presented with a pop-up window where they can set their search criteria.

Questions:
Is there a minimum set of search criteria that the user must enter? (e.g., City or State, etc) Or  do we want user to return all results in the database if they don't enter any search criteria?
What if they want to search in multiple cities (e.g., San Diego, Escondido, Chula Vista) or maybe they want to know if what is available for rent state wide? 
Do we want the user to be able to search within a radius of X miles of their chosen/"sensed" location?

**Comment by zos-jeff-olen** [comment]
Let's just close this for now.
