### ISSUE TITLE
Miscellaneous Map Popover issues

### ISSUE THREAD

**Issue by jetamartin** [notch8/rent_my_thing#86]
1) Make Popover directly aligned with corresponding marker
- Popup is not directly aligned with marker (a little off center) so when you have mulitple markers in close proximity on the map as drawn (i.e.,, not manually  zoomed) this "misallignment" makes it a little more challenging to hover over the marker and get the right popover to appear. 
  2) Popover "cutoff" when at top of page
  If map marker is near the top of the page the popover will not be completely visible because it extends beyond the view and cannot be seen.

**Comment by kosmicowboy** [comment]
duplicate issue
